### ISSUE TITLE
Config Parser default encoding should be utf-8

### ISSUE THREAD

**Issue by return42** [mozilla-services/konfig#11]
With non ascii characters in `config-files.ini` (e.g. in comments) we get a `UnicodeDecodeError: 'ascii' codec can't decode byte ....`. this is because the default encoding of the configparser is ascii. My suggestion is to change the default encoding to utf-8. 

This would be done by setting `"utf-8"` in line 90 in `konfig/__init__.py`. Change from:

``` python
        if isinstance(filename, basestring):
            self.filename = filename
            self.read(filename)
```

to:

``` python
        if isinstance(filename, basestring):
            self.filename = filename
            self.read(filename, "utf-8")
```

It's a small change with huge effect outside of the ascii-world ;-)

**Comment by tarekziade** [comment]
@return42 I can't reproduce the issue. Can you look at the test I have added ? Thx

**Comment by return42** [comment]
@tarekziade thats wired, I can't reproduce neither ... so I close this issue / sorry for the noise.

FWIW, I try to make the sync-server components python3 compliant. Today I forked konf:

  - https://github.com/mozilla-services/konfig/network

May you are interested, then take a look at my 'six' branch. Yes, konf seems already py3 compliant, but there are some improvements to build and test.

Do you know about any efforts to make the sync-server suite py3 compliant?

Thanks!
