### ISSUE TITLE
Add support for loading python packages resources as a [DEFAULT][extends] and [DEFAULT][overrides] 

### ISSUE THREAD

**Issue by enkidulan** [mozilla-services/konfig#15]
Having `extends` and `overrides` in config files are efficient, but it will be even more beneficial if it would be possible to specify python package resource files in extends/overrides. For example basic config may be shipped with the package and then easily be extended/overridden locally on destination server:

    [DEFAULT]
    extends = resource://mypackage/cofigs/public.ini

    [database]
    password = secret

That is kind of how [websauna](https://websauna.org/docs/api/websauna.utils.configincluder.html?highlight=config#websauna.utils.configincluder.IncludeAwareConfigParser) does things, if you interested in having this feature I can make a PR.

**Comment by tarekziade** [comment]
that's pretty awseome. thanks @enkidulan
